Resolve GSOD introduced in IconBarAdd commit f8522ea9 Thanks for reporting IMS
[eFilePushThread] current_span_remaining: 1073741696 m_blocksize: 188 rest: 0
[eFilePushThread] current_span_remaining: 1073741696 m_blocksize: 188 rest: 0
Traceback (most recent call last):
  File /usr/lib/enigma2/python/Screens/InfoBarGenerics.py, line 535, in doTimerHide
    self.hide()
  File /usr/lib/enigma2/python/Screens/Screen.py, line 147, in hide
    x()
  File /usr/lib/enigma2/python/Screens/InfoBarGenerics.py, line 448, in __onHide
    self.InfoBarAdds.hide()
AttributeError: 'MoviePlayer' object has no attribute 'InfoBarAdds'
[ePyObject] (CallObject(<bound method InfoBarShowHide.doTimerHide of <class 'Screens.InfoBar.MoviePlayer'>>,()) failed)

(cherry picked from commit 16c4283b6519ca4a0179b19d044e080c42e288a6)
Thanks to @Littlesat