Fix MenuList initialize in FIFOList This fix AttributeError: 'FIFOList' object has no attribute 'l' after OpenPLi/enigma2@fb23b13 Thx Amai for report.
(cherry picked from commit 008a4d487ebc5479a1a20ce0c31c1f51ce571af9)
Thanks to @Taapat and @teamblue-e2